version: '2'
services:
  chia_reporter:
    image: chia-reporter
    container_name: chia-report
    volumes:
      - ./certs:/go/src/app/certs
      - ./config.json:/go/src/app/config.json
    restart: unless-stopped